In [7]:
import numpy as np  # import a package (numpy)
import cv2  #  opencv

#!pip list  # list all the packages that have been pre-installed

!python --version  # show python version
print(cv2.__version__)  # show opencv version
print(np.__version__)  #show numpy version



Python 3.10.12
4.8.0
1.23.5


# Test if a GPU is available

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import tensorflow as tf
tf.test.gpu_device_name()

''

# Install a package/library

In [ ]:
%pip install keras  # In fact, keras should have been pre-installed in Colab

# Basic data types


In [ ]:
x = 5  # int
y = 1.5  # float
z = True  # boolean
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'bool'>


In [ ]:
machine = 'machine'
mv = machine + '_' + 'vision'  # concatenation of strings
print(mv)
print(type(mv))

machine_vision
<class 'str'>


* Please refer to some of the [useful string methods](https://docs.python.org/release/3.6.9/library/stdtypes.html#string-methods)

# Lists, Dictionaries, Sets and Tuples

In [ ]:
a = [1, 2, 3]
b = ['x', 'y', 'z']
a[1] = 'z'

print(a)
print(b)

[1, 'z', 3]
['x', 'y', 'z']


* More on list [here](https://docs.python.org/release/3.6.9/tutorial/datastructures.html#more-on-lists)
* Read about [Dictionaries](https://docs.python.org/release/3.6.9/library/stdtypes.html#mapping-types-dict), [Sets](https://docs.python.org/release/3.6.9/library/stdtypes.html#set-types-set-frozenset) and [Tuples](https://docs.python.org/release/3.6.9/library/stdtypes.html?highlight=tuple#tuples) yourself

# Numpy

Create a numpy array

In [8]:
a = np.arange(12)
a1 = np.arange(2, 20, 3)  # Return evenly spaced values within a given interval.
b = np.diag(a)  # Extract a diagonal or construct a diagonal array.
print(a)
print(a1)
print(b)

a2 = np.arange(1, 50, 2)
b2 = np.diag(a2)
print(b2)
c=b2[3:24,3:24]
print(c)
d=np.scale

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 2  5  8 11 14 17]
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11]]
[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

Reshape a numpy array

In [ ]:
a = a.reshape(3,4)
print(a)
print('The shape of the array is: ' + str(a.shape))
print('The type of the elements: ' + a.dtype.name)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The shape of the array is: (3, 4)
The type of the elements: int64


Add a number to all elements in an array

In [ ]:
a = a + 5
print(a)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Slicing

In [ ]:
c = a[0:2, 2]
print(c)


[ 7 11]


* More on numpy [here](https://numpy.org/doc/1.18/reference/index.html)